# Generated by Django 5.2.13 on 2026-04-15 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
        migrations.AddField(
            model_name='project',
            name='developers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'profile__role': 'DEV'}, related_name='assigned_dev_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='functional_analysts',
            field=models.ManyToManyField(blank=True, limit_choices_to={'profile__role': 'FA'}, related_name='assigned_fa_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
