# Generated by Django 5.2.13 on 2026-04-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_remove_ticket_description_ticket_api_or_other_datas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketremark',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('PENDING_REVIEW', 'Pending FA Review'), ('DONE', 'Done')], default='TODO', max_length=20),
        ),
    ]
