# Generated by Django 5.2.13 on 2026-04-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_userprofile_full_name_userprofile_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='actual_time_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
