# Generated by Django 5.2.13 on 2026-05-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_project_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
